using System;

public class Class1
{  /// <summary>
/// this is a class for to check if comment sare generated by the class or not
/// now will write some code to check the performance
/// <returns>
/// print this is class method for calling from the main class
/// </returns>
/// </summary>
	public Class1()
	{
		Console.write("This is class method for calling from the main class");
	}
}
